apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pithos-storage
  namespace: pithos
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 10Gi
